name: Slither Analysis
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Code analysis
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          node-version: 18
          target: "challenge"
          sarif: results.sarif
          fail-on: none
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}