name: Slither Analysis
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Code analysis
        uses: crytic/slither-action@v0.3.0
        with:
          node-version: 18
          target: "challenge"